apiVersion: v1
kind: Service
metadata:
  name: test-project
spec:
  type: NodePort
  ports:
    - port: 8080
  selector:
    app: test-project
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-project
spec:
  replicas: 2
  selector:
    matchLabels:
      app: test-project
  template:
    metadata:
      labels:
        app: test-project
    spec:
      containers:
        - name: test
          image: nginx:1.14.2
          ports:
            - containerPort: 80
